- hosts: all
  gather_facts: no
  tasks:
    - name: "Delete deployment"
      community.kubernetes.k8s:
        state: absent
        kubeconfig: "{{ kubeconfig }}"
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: "{{ deployment_name }}"
            namespace: "{{ deployment_namespace }}"