tosca_definitions_version: tosca_simple_yaml_1_3

imports:
  - kubernetes/main.yaml

topology_template:

  node_templates:

    minikube:
      type: sodalite.nodes.Kubernetes.Cluster
      properties:
        kubeconfig: ~/.kube/config
      attributes:
        public_address: # Without this, it yields: Cannot use an unset value: public_address

    nginx-deployment:
      type: sodalite.nodes.Kubernetes.Kind.Deployment
      properties:
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-deployment
            namespace: default
          spec:
            selector:
              matchLabels:
                app: nginx
            replicas: 2
            template:
              metadata:
                labels:
                  app: nginx
                  other: label
              spec:
                containers:
                  - name: nginx
                    image: nginx:1.16.1
                    ports:
                      - containerPort: 80
      requirements:
        - host: minikube

    nginx-deployment-via-definition:
      type: sodalite.nodes.Kubernetes.Definition.File
      properties:
        path: { get_artifact: [ SELF, def_file ] }
      artifacts:
        def_file:
          type: tosca.artifacts.File
          file: files/nginx-def.yaml
      requirements:
        - host: minikube

    ####################################################
    # Helm
    ####################################################
    mysql-deployment-via-helm:
      type: sodalite.nodes.Kubernetes.Definition.Helm
      properties:
        name: mysql-release-1-from-helm
        namespace: default
        chart: stable/mysql
        chart_version: latest
        repo_name: stable
        repo_url: "https://charts.helm.sh/stable"
        keep_repo: false
        values_files:
          - helm-values-1.yaml
          - helm-values-2.yaml
          # - { get_artifact: [ SELF, helm-values-1 ] } # error: opera cannot retrieve nested TOSCA functions
          # - { get_artifact: [ SELF, helm-values-2 ] } # error: opera cannot retrieve nested TOSCA functions
        values:
          replicas: 2
        # repo_url: "http://github.com/helm/charts.git"
      artifacts:
        helm-values-1:
          type: tosca.artifacts.File
          file: files/helm-values-1.yaml
        helm-values-2:
          type: tosca.artifacts.File
          file: files/helm-values-2.yaml
      requirements:
        - host: minikube