---
- name: Refresh token and update env
  import_playbook: egi_refresh_token.yml
  when: env.checkin_env is defined

- hosts: all
  gather_facts: no

  tasks:
    - name: Delete keypair
      os_keypair:  
        name: "{{ name }}"
        state: absent
      ignore_errors: True
      environment: "{{ os_env if os_env is defined }}"