---
- name: Refresh token and update env
  import_playbook: egi_refresh_token.yml
  when: env.checkin_env is defined

- hosts: all
  gather_facts: no
  
  tasks:
    - name: Create keypair
      os_keypair:  
        name: "{{ name }}"
        public_key: "{{ public_key }}"
        state: present
      environment: "{{ os_env if os_env is defined }}"