---
- hosts: all
  become: no
  gather_facts: no
  tasks:
# ===============================================================
# Step1: Create Application
# ===============================================================
    - name: create application
      uri:
        method: POST
        url: "{{alde_host}}/api/v1/applications"
        body_format: json
        body:
          name: "{{app_name}}"
        return_content: yes
        status_code: 201
      register: content
    - name: parse application ID
      set_fact:
        application_id: "{{ content.json.id }}"

# ===============================================================
# Step2: Create Executable
# ===============================================================
    - name: create executable
      uri:
        method: POST
        url: "{{alde_host}}/api/v1/executables"
        body_format: json
        body:
          application_id: "{{application_id}}"
          status: COMPILED
          compilation_type: SINGULARITY_PM
          executable_file: "{{pbs_path}}"
        return_content: yes
        status_code: 201
      register: content
    - name: parse executable ID
      set_fact:
        executable_id: "{{ content.json.id }}"

# ===============================================================
# Step3: Create Deployment
# ===============================================================
    - name: create deployment
      uri:
        method: POST
        url: "{{alde_host}}/api/v1/deployments"
        body_format: json
        body:
          executable_id: "{{executable_id}}"
          testbed_id: "{{testbed_id}}"
        return_content: yes
        status_code: 201
      register: content

# ===============================================================
# Step4: Create Execution Configuration
# ===============================================================
    - name: create execution configuration
      uri:
        method: POST
        url: "{{alde_host}}/api/v1/execution_configurations"
        body_format: json
        body:
          application_id: "{{application_id}}"
          executable_id: "{{executable_id}}"
          testbed_id: "{{testbed_id}}"
          execution_type: TORQUE:QSUB
        return_content: yes
        status_code: 201
      register: content
    - name: parse configuration ID
      set_fact:
        configuration_id: "{{ content.json.id }}"

# ===============================================================
# Step5: Create Execution Configuration
# ===============================================================
    - name: launch execution configuration
      uri:
        method: PATCH
        url: "{{alde_host}}/api/v1/execution_configurations/{{configuration_id}}"
        body_format: json
        body:
          launch_execution: true
        return_content: yes
        status_code: 200
      register: content